/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
public class DlgSobre extends java.awt.Dialog {

    /**
     * Creates new form DlgSobre
     */
    public DlgSobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("ZaShoes");
        setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/logo.png")).getImage());
        this.setSize(new Dimension(800,390));
        this.setLocationRelativeTo(parent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationRelativeTo(null);
        setModal(true);
        setResizable(false);
        setTitle("Sobre Facturacion APR");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 150));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 255, 204));
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n<br>  <br/>\n<br>  <br/>\n<CENTER> <b>UNIVERSIDAD TECNICA AMBATO</b></CENTER>\n<CENTER> <b>COMPUTACION VISUAL</b></CENTER>\n<CENTER> <b>PROYECTO FINAL</b></CENTER>\n    <p style=\"margin-top: 2\">\r\n\n      <CENTER>SISTEMA ELABORADO PARA EL MEJORAMIENTO DE UNA ZAPATERIA</CENTER>\n<br>  <br/>\n                <CENTER> <b>INTEGRANTES</b></CENTER>\n <CENTER> <b>WILMAR MINDA - FAUSTO NAVARRETE </b> </CENTER>\n    </p>\r\n    <h3 style=\"font-weidth:bold;\">Enlaces</h3>\n    <ul>\n      <li>Página Web:<a href=\"http://www.uta.edu.ec/v3.2/uta/\">http://www.uta.edu.ec/v3.2/uta/</a></li>\n<li>FaceBook:<a href=\"https://www.facebook.com/profile.php?id=100017497500968\">https://www.facebook.com/profile.php?id=100017497500968</a></li>\t\t\n    <ul/>\n  </body>\r\n</html>\r\n");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/banderin.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      setVisible(false);
      dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
